// Khiem Do
import java.util.*; 


public class Project2 { // Reminder// int inside the loop to loop will die when loop is finished
    public static void main(String[] args) {
        Scanner scnr = new Scanner(System.in);

        ArrayList<Integer> rand_nums = new ArrayList<Integer>(); // created a list of numbers
        for (int i = 1; i <= 100; i++) // from 1 to 100
            rand_nums.add(i); // add each number generated by the loop into the list (this method will make
                              // sure that random same numbers are impossibly happen)

        ArrayList<String> rand_questions = new ArrayList<String>();
        String ques0 = "what is the smallest number? ";
        String ques1 = "what is the largest number? ";
        String ques2 = "what is the median number? ";
        String ques3 = "what is the sum of all numbers? ";
        rand_questions.add(ques0);
        rand_questions.add(ques1); // assigned each question into a string to manipulate later
        rand_questions.add(ques2);
        rand_questions.add(ques3);
        Collections.shuffle(rand_questions); // shuffle to positions of questions

        Random rand = new Random(); // create instance of Random class
        int score = 0; // outside the loop// to print score of player at the end

        for (int i = 0; i < 10; ++i) { // print 10 times

            int randomIndex = rand.nextInt(rand_questions.size()); // a random number // from size of the,list (0-4)
                                                                   // 0,1,2,3
            String randomQues = rand_questions.get(randomIndex); // Get string from random int // random int from size
                                                                 // of the list

            System.out.print("The numbers for this round are: ");
            Collections.shuffle(rand_nums); // shuffle is to switch the position of numbers in a list
            for (int j = 0; j < 3; j++) // loop to print 3 numbers
                System.out.print(rand_nums.get(j) + " "); // list.get(j) method is to get a number from the list// list
                                                          // here is rand_nums
            System.out.print("\n");
            int num1 = rand_nums.get(0);
            int num2 = rand_nums.get(1); // identify positions of numbers
            int num3 = rand_nums.get(2);

            int largest_num = 0;
            if (num1 > num2 && num1 > num3) { // if num1 is largest
                largest_num = num1;
            } else if (num2 > num3 && num2 > num1) { // if num2 is largest
                largest_num = num2;
            } else { // if num3 is largest
                largest_num = num3;
            }

            int smallest_num = 0;
            // smallest_num = Math.min(num1, Math.min(num2,num3));
            if (num1 < num2 && num1 < num3) { // if num1 is smallest
                smallest_num = num1;
            } else if (num2 < num1 && num2 < num3) { // if num2 is smallest
                smallest_num = num2;
            } else { // if num3 is smallest
                smallest_num = num3;
            }

            int median_num = 0;
            if ((num1 > num3 && num1 < num2) || (num1 > num2 && num1 < num3)) { // if num1 is median
                median_num = num1;
            } else if ((num2 > num3 && num2 < num1) || (num2 > num1 && num2 < num3)) { // if num2 is median
                median_num = num2;
            } else if ((num3 > num2 && num3 < num1) || (num3 < num2 && num3 > num1)) { // if num3 is median
                median_num = num3;
            }

            int sum_num = num1 + num2 + num3; // sum of all numbers

            try {
                Thread.sleep(3000);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }

            for (int k = 1; k <= 100; k++) // loop to print blank line
                System.out.print("\n");

            if (randomIndex == 0) { // return question about smallest num
                System.out.print(ques0); // print question
                int answer = scnr.nextInt();
                if (answer == smallest_num) {
                    System.out.println("That's right!");
                    score++; // score go up 1 every correct answer
                } else {
                    System.out.println("That's wrong. The correct answer was " + smallest_num);
                }
            }

            if (randomIndex == 1) { // return question about largest num
                System.out.print(ques1);
                int answer = scnr.nextInt();
                if (answer == largest_num) {
                    System.out.println("That's right!");
                    score++;
                } else {
                    System.out.println("That's wrong. The correct answer was " + largest_num);
                }
            }

            if (randomIndex == 2) { // return question about median num
                System.out.print(ques2);
                int answer = scnr.nextInt();
                if (answer == median_num) {
                    System.out.println("That's right!");
                    score++;
                } else {
                    System.out.println("That's wrong. The correct answer was " + median_num);
                }
            }

            if (randomIndex == 3) { // return question about sum
                System.out.print(ques3);
                int answer = scnr.nextInt();
                if (answer == sum_num) {
                    System.out.println("That's right!");
                    score++;
                } else {
                    System.out.println("That's wrong. The correct answer was " + sum_num);
                }
            }
        }
        System.out.println("You got " + score + " out of 10 right.");

    }
}
